---
- name: configure sshd
  become: "yes"
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: "yes"
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sshd
  tags:
    - sshd

- name: register /etc/default/motd-news
  stat:
    path: /etc/default/motd-news
  register: motd_news
  tags:
    - motd

- name: remove banner files
  become: "yes"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: disable motd-news
  become: "yes"
  lineinfile:
    regexp: "^ENABLED="
    line: "ENABLED=0"
    dest: /etc/default/motd-news
    mode: 0644
    state: present
    create: "no"
    backrefs: "yes"
  notify:
    - mask motdnews timer
    - mask motdnews service
  when: ansible_os_family == "Debian" and motd_news.stat.exists
  tags:
    - motd
